import { Team, Competition } from './types';

export const TEAMS: Team[] = [
    { id: 1, name: 'Korean White Tigers', nameParts: ['Korean', 'White Tigers'], country: 'South Korea', iso_name: 'KOR', bgColor: '#EAEAEA', textColor: '#001F60', photo_url: '/team-photos/south_korea.png' },
    { id: 2, name: 'USA Eagles', nameParts: ['USA', 'Eagles'], country: 'USA', iso_name: 'USA', bgColor: '#002868', textColor: '#FFFFFF', photo_url: '/team-photos/united_states.png' },
    { id: 3, name: 'Dutch Lions', nameParts: ['Dutch', 'Lions'], country: 'Netherlands', iso_name: 'NLD', bgColor: '#F47920', textColor: '#FFFFFF', photo_url: '/team-photos/netherlands.png' },
    { id: 4, name: 'Belgium Ice Bears', nameParts: ['Belgium', 'Ice Bears'], country: 'Belgium', iso_name: 'BEL', bgColor: '#F0F0F0', textColor: '#000000', photo_url: '/team-photos/belgium.png' },
    { id: 5, name: 'Canadian Ice Maples', nameParts: ['Canadian', 'Ice Maples'], country: 'Canada', iso_name: 'CAN', bgColor: '#1A1A1A', textColor: '#FF0000', photo_url: '/team-photos/canada.png' },
    { id: 6, name: 'Chinese Loongs', nameParts: ['Chinese', 'Loongs'], country: 'China', iso_name: 'CHN', bgColor: '#EE1C25', textColor: '#FFFF00', photo_url: '/team-photos/china.png' },
    { id: 7, name: 'Polish Hussars', nameParts: ['Polish', 'Hussars'], country: 'Poland', iso_name: 'POL', bgColor: '#FFFFFF', textColor: '#DC143C', photo_url: '/team-photos/poland.jpg' },
    { id: 8, name: 'Italian Gladiators', nameParts: ['Italian', 'Gladiators'], country: 'Italy', iso_name: 'ITA', bgColor: '#0055A4', textColor: '#FFFFFF', photo_url: '/team-photos/italy.png' },
    { id: 9, name: 'Kazakh Nomads', nameParts: ['Kazakh', 'Nomads'], country: 'Kazakhstan', iso_name: 'KAZ', bgColor: '#1E2952', textColor: '#F0E14A', photo_url: '/team-photos/kazakhstan.jpg' },
    { id: 10, name: 'Japanese Ninjas', nameParts: ['Japanese', 'Ninjas'], country: 'Japan', iso_name: 'JPN', bgColor: '#FFFFFF', textColor: '#BC002D', photo_url: '/team-photos/japan.jpg' },
    { id: 11, name: 'Hungarian Falcons', nameParts: ['Hungarian', 'Falcons'], country: 'Hungary', iso_name: 'HUN', bgColor: '#231F20', textColor: '#FFFFFF', photo_url: '/team-photos/hungary.jpg' },
    { id: 12, name: 'French Roosters', nameParts: ['French', 'Roosters'], country: 'France', iso_name: 'FRA', bgColor: '#002395', textColor: '#FFFFFF', photo_url: '/team-photos/france.jpg' },
    { id: 13, name: 'British Royals', nameParts: ['British', 'Royals'], country: 'Great Britain', iso_name: 'GBR', bgColor: '#012169', textColor: '#FFFFFF', photo_url: '/team-photos/great_britain.jpg' },
    { id: 14, name: 'Ukrainian Wild Cats', nameParts: ['Ukrainian', 'Wild Cats'], country: 'Ukraine', iso_name: 'UKR', bgColor: '#0057B7', textColor: '#FFDD00', photo_url: '/team-photos/ukraine.jpg' },
    { id: 15, name: 'Croatian Dalmatians', nameParts: ['Croatian', 'Dalmatians'], country: 'Croatia', iso_name: 'HRV', bgColor: '#1C1C1C', textColor: '#FFFFFF', photo_url: '/team-photos/croatia.jpg' },
    { id: 16, name: 'German Wolves', nameParts: ['German', 'Wolves'], country: 'Germany', iso_name: 'DEU', bgColor: '#1C1C1C', textColor: '#FFCE00', photo_url: '/team-photos/germany.jpg' },
    { id: 17, name: 'Czechia Ice Spiders', nameParts: ['Czechia', 'Ice Spiders'], country: 'Czechia', iso_name: 'CZE', bgColor: '#003153', textColor: '#FFFFFF', photo_url: '/team-photos/czechia.jpg' },
    { id: 18, name: 'Bulgarian Kings', nameParts: ['Bulgarian', 'Kings'], country: 'Bulgaria', iso_name: 'BGR', bgColor: '#222222', textColor: '#FFFFFF', photo_url: '/team-photos/bulgaria.jpg' },
    { id: 19, name: 'Latvian Golden Stars', nameParts: ['Latvian', 'Golden Stars'], country: 'Latvia', iso_name: 'LVA', bgColor: '#FDFBF8', textColor: '#A4343A', photo_url: '/team-photos/latvia.png' },
    { id: 20, name: 'Australian Racing Roos', nameParts: ['Australian', 'Racing Roos'], country: 'Australia', iso_name: 'AUS', bgColor: '#006A4E', textColor: '#FFCD00', photo_url: '/team-photos/australia.jpg' },
    { id: 21, name: 'Turkish Anatolian Pars', nameParts: ['Turkish', 'Anatolian Pars'], country: 'Turkey', iso_name: 'TUR', bgColor: '#212121', textColor: '#FFFFFF', photo_url: '/team-photos/turkey.png' },
    { id: 22, name: 'Hong Kong Ice Qilins', nameParts: ['Hong Kong', 'Ice Qilins'], country: 'Hong Kong', iso_name: 'HKG', bgColor: '#E40001', textColor: '#FFFFFF', photo_url: '/team-photos/hong-kong.jpg' },
    { id: 23, name: 'New Zealand Ice Keas', nameParts: ['New Zealand', 'Ice Keas'], country: 'New Zealand', iso_name: 'NZL', bgColor: '#121212', textColor: '#FFFFFF', photo_url: '/team-photos/new-zealand.jpg' },
    { id: 24, name: 'Irish Wolf Hounds', nameParts: ['Irish', 'Wolf Hounds'], country: 'Ireland', iso_name: 'IRL', bgColor: '#009A44', textColor: '#FFFFFF', photo_url: '/team-photos/ireland.png' },
    { id: 25, name: 'Swiss Ibex', nameParts: ['Swiss', 'Ibex'], country: 'Switzerland', iso_name: 'CHE', bgColor: '#DA291C', textColor: '#FFFFFF', photo_url: '/team-photos/switzerland.jpg' },
    { id: 26, name: 'Norwegian Vikings', nameParts: ['Norwegian', 'Vikings'], country: 'Norway', iso_name: 'NOR', bgColor: '#BA0C2F', textColor: '#FFFFFF', photo_url: '/team-photos/norway.jpg' },
    { id: 27, name: 'Thai Elephants', nameParts: ['Thai', 'Elephants'], country: 'Thailand', iso_name: 'THA', bgColor: '#3C3658', textColor: '#FFFFFF', photo_url: '/team-photos/thailand.jpg' },
    { id: 28, name: 'Singapore Gazelles', nameParts: ['Singapore', 'Gazelles'], country: 'Singapore', iso_name: 'SGP', bgColor: '#ED2939', textColor: '#FFFFFF', photo_url: '/team-photos/singapore.jpg' },
    { id: 29, name: 'Philippine Tamaraws', nameParts: ['Philippine', 'Tamaraws'], country: 'Philippines', iso_name: 'PHL', bgColor: '#0038A8', textColor: '#FCD116', photo_url: '/team-photos/philippines.png' },
];


export const COMPETITIONS = [
  {
    id: 1,
    title: 'World Cup 1',
    location: 'Montréal',
    country: 'Canada',
    date: 'Oct 26-27, 2024',
    details: 'Maurice Richard Arena',
  },
  {
    id: 2, 
    title: 'World Cup 2', 
    location: 'Montréal', 
    country: 'Canada', 
    date: 'Nov 2-3, 2024', 
    details: 'Maurice Richard Arena'
  },
  { 
    id: 3, 
    title: 'World Cup 3', 
    location: 'Beijing', 
    country: 'China', 
    date: 'Dec 7-8, 2024', 
    details: 'Capital Indoor Stadium',
  },
  { 
    id: 4, 
    title: 'World Cup 4', 
    location: 'Seoul', 
    country: 'South Korea', 
    date: 'Dec 14-15, 2024', 
    details: 'Mokdong Ice Rink',
  },
  { 
    id: 5, 
    title: 'World Cup 5', 
    location: 'Tilburg', 
    country: 'Netherlands', 
    date: 'Feb 8-9, 2025', 
    details: 'Ireen Wüst IJsbaan',
  },
  { 
    id: 6, 
    title: 'World Cup 6', 
    location: 'Milan', 
    country: 'Italy', 
    date: 'Feb 15-16, 2025', 
    details: 'Forum di Milano',
  }
];